# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34dfcfdaff4f0bc504550f74ac05c33f74f5a0f0d8266c169003bf7c43786b1329a522ae7761afe8ad6f82a5be79537ae051a02a6737e8d8c2a022aac745b9a

test:
  secret_key_base: 5298001c5280a0be7028ed7f35d4770c684ab3992996218c28e552aa2c9282e540fb2f91786cd8f45a91a5716165fbdfde4e9923938702abc410d5aad0539e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
